# 全局上下文
worker_processes 1;  # 设置工作进程数

# 事件块
events {
    worker_connections 1024;  # 设置每个工作进程的最大连接数
}

# HTTP 块
http {
    include mime.types;
    default_type application/octet-stream;

    # 服务器块
    server {
        listen 3001;
        server_name localhost;

        # 根目录的静态文件
        location / {
            root /usr/share/nginx/html;
            try_files $uri /index.html;  # 确保单页面应用的路由正常工作
        }
    }
}


